// src/world/scene_import.rs
// Build-time expansion: SceneImport -> Texture / Material / Mesh / Model /
// Prop / Camera3D. The heavy lifting (parsing, triangulation, transform
// composition) lives in `crate::import`; this pass reads the import's
// args, threads them through, and substitutes each SceneImport entry with its
// generated entry list. The result is content-addressed by source contents +
// options, so an unchanged source skips the parse entirely on a rebuild.

use std::collections::HashSet;

use super::expand::{asset_name, type_norm};
use crate::import::{ImportOptions, entries_from_scene, sanitize_name};

// Replace every SceneImport asset with the asset entries its source file
// expands to. Generated names are prefixed with the import's (unique) asset
// name, so they never collide with hand-authored assets; a collision is a hard
// error. The framed Camera3D is emitted only when the world declares no camera
// of its own (yours always wins) and `emit_camera` is not disabled.
pub(crate) fn expand_scene_imports(assets: &mut Vec<serde_json::Value>) -> Result<(), String> {
    if !assets.iter().any(|v| type_norm(v) == "sceneimport") {
        return Ok(());
    }

    // A user-declared camera always wins the runtime's first-Camera3D query, so
    // an import frames its own camera only when the world declares none.
    // CameraShot expands to a Camera3D later, so it counts as a declared camera
    // here even though it hasn't expanded yet.
    let world_has_camera = assets
        .iter()
        .any(|v| matches!(type_norm(v).as_str(), "camera3d" | "camerashot"));
    // Track whether a framed camera has already been emitted so two imports
    // don't each add a competing one.
    let mut camera_emitted = false;

    // Names already in use: authored assets plus entries generated by earlier
    // imports. A generated name landing on one of these is rejected.
    let mut taken: HashSet<String> = assets
        .iter()
        .filter(|v| type_norm(v) != "sceneimport")
        .map(asset_name)
        .filter(|n| !n.is_empty())
        .collect();

    let mut result: Vec<serde_json::Value> = Vec::new();
    for value in assets.drain(..) {
        if type_norm(&value) != "sceneimport" {
            result.push(value);
            continue;
        }

        let import_name = asset_name(&value);
        let args = value
            .get("args")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));
        let source = args
            .get("source")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        if source.is_empty() {
            return Err(format!("SceneImport '{}': missing `source`", import_name));
        }

        let want_camera = args
            .get("emit_camera")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);
        let opts = ImportOptions {
            name_prefix: sanitize_name(&import_name),
            texture_max_size: args
                .get("texture_max_size")
                .and_then(|v| v.as_u64())
                .unwrap_or(512) as u32,
            emissive_map_strength: args
                .get("emissive_map_strength")
                .and_then(|v| v.as_f64())
                .unwrap_or(3.0) as f32,
            emit_camera: want_camera && !world_has_camera && !camera_emitted,
        };

        let entries = expand_one(&source, &opts)
            .map_err(|e| format!("SceneImport '{}': {}", import_name, e))?;

        for entry in entries {
            let name = asset_name(&entry);
            if !name.is_empty() && !taken.insert(name.clone()) {
                return Err(format!(
                    "SceneImport '{}': generated asset name '{}' collides with an existing \
                     asset; rename the import or the conflicting asset",
                    import_name, name
                ));
            }
            if type_norm(&entry) == "camera3d" {
                camera_emitted = true;
            }
            result.push(entry);
        }
    }

    *assets = result;
    Ok(())
}

// Generate one import's entries, served from the content-addressed cache when
// the source file and options are unchanged. The cache stores the generated
// JSON entry list, so a rebuild of an unchanged import never re-parses the
// (potentially very large) source file. Best-effort: a corrupt or absent entry
// falls back to a fresh expansion.
fn expand_one(source: &str, opts: &ImportOptions) -> std::io::Result<Vec<serde_json::Value>> {
    let key_args = serde_json::json!({
        "prefix": opts.name_prefix,
        "texture_max_size": opts.texture_max_size,
        "emissive_map_strength": opts.emissive_map_strength,
        "emit_camera": opts.emit_camera,
    });
    let key = crate::cache::expand_key(source, &key_args);

    if let Some(bytes) = crate::cache::load(&key)
        && let Ok(entries) = serde_json::from_slice::<Vec<serde_json::Value>>(&bytes)
    {
        return Ok(entries);
    }

    let entries = entries_from_scene(source, opts)?;
    if let Ok(bytes) = serde_json::to_vec(&entries) {
        crate::cache::store(&key, &bytes);
    }
    Ok(entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    // A world with no SceneImport is left untouched.
    #[test]
    fn passes_through_without_imports() {
        let mut assets = vec![serde_json::json!({"name":"x","type":"Logger","args":{}})];
        expand_scene_imports(&mut assets).unwrap();
        assert_eq!(assets.len(), 1);
        assert_eq!(assets[0]["type"], "Logger");
    }

    #[test]
    fn missing_source_is_an_error() {
        let mut assets = vec![serde_json::json!({
            "name": "scene", "type": "SceneImport", "args": {}
        })];
        let err = expand_scene_imports(&mut assets).unwrap_err();
        assert!(err.contains("missing `source`"));
    }

    #[test]
    fn unsupported_source_format_is_an_error() {
        let mut assets = vec![serde_json::json!({
            "name": "scene", "type": "SceneImport", "args": {"source": "thing.txt"}
        })];
        let err = expand_scene_imports(&mut assets).unwrap_err();
        // The import name is included so the user knows which entry failed.
        assert!(err.contains("scene"));
        assert!(err.contains(".txt"));
    }
}
