#pragma once

/* Auto-generated by cbindgen from src/ffi.rs. Do not edit. */

int cn_init(void);

int cn_connect(const char *ws_url, const char *account_id);

void cn_disconnect(void);

int cn_is_connected(void);

int cn_set_server_config(const char *server, const char *account_id);

int cn_build_world(const char *assets_path, const char *world_jsonl_path);

int cn_add(const char *assets_path,
           const char *world_jsonl_path,
           const char *target,
           const char *name_override);

int cn_add_with_template(const char *assets_path,
                         const char *world_jsonl_path,
                         const char *target,
                         const char *name_override,
                         const char *template_);

int cn_rm(const char *assets_path, const char *world_jsonl_path, const char *name);

int cn_check_world(const char *world_jsonl_path);

int cn_preview_start(void *ns_view, const char *assets_path, const char *world_jsonl_path);

void cn_preview_stop(void);

int cn_preview_step(void);

int cn_run_world_blocking(const char *assets_path);

int cn_run_world_blocking_in_view(void *ns_view, const char *assets_path);

void cn_stop_world_blocking(void);
